# Generated by Django 5.0.6 on 2024-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothesmodel",
            name="size",
            field=models.CharField(
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "Xl"),
                    ("xxl", "XXL"),
                ],
                default=1,
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
