# Generated by Django 5.0.6 on 2024-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0002_clothesmodel_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothesmodel",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
