# Generated by Django 5.1.2 on 2024-11-05 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clothes", "0003_clothesmodel_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothesmodel",
            name="back_image",
        ),
        migrations.RemoveField(
            model_name="clothesmodel",
            name="front_image",
        ),
    ]
